title: System Performance&Safety
author: Rehan MALAK
# email: your-email@domain.com
theme: jekyll-theme-slate
repository: Rehan-MALAK/SystemPerformanceAndSafety
github:
  is_project_page false
description: > # this means to ignore newlines until "baseurl:"
  Rehan MALAK page

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Rehan-MALAK # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
